Repository NAFTeam/NAFF, pull requests merged in 2021-12, with the labels that each got.

#88 Various Improvements to gateway / startup / dispatching
  dis_snek/client.py
  dis_snek/errors.py
  dis_snek/event_processors/_template.py
  dis_snek/event_processors/channel_events.py
  dis_snek/event_processors/guild_events.py
  dis_snek/event_processors/member_events.py
  dis_snek/event_processors/message_events.py
  dis_snek/event_processors/reaction_events.py
  dis_snek/event_processors/role_events.py
  dis_snek/event_processors/stage_events.py
  dis_snek/event_processors/thread_events.py
  dis_snek/event_processors/user_events.py
  dis_snek/gateway.py
  dis_snek/mixins/serialization.py
  dis_snek/models/discord_objects/guild.py
  dis_snek/models/discord_objects/message.py
  dis_snek/models/events/internal.py
Labels: enhancement, breaking

#101 Improvements to doc templates
  docs/templates/python/material/attr_attributes.html
  docs/templates/python/material/children.html
  docs/templates/python/material/class.html
  docs/templates/python/material/function.html
  docs/templates/python/material/method.html
  docs/templates/python/material/signature.html
Labels: documentation

#107 Add default params for edit channel
  dis_snek/models/discord_objects/channel.py
Labels: enhancement

#106 Add VoiceStateUpdate event
  dis_snek/client.py
  dis_snek/event_processors/voice_events.py
  dis_snek/models/__init__.py
  dis_snek/models/discord_objects/voice_state.py
  dis_snek/models/events/discord.py
  dis_snek/smart_cache.py
Labels: enhancement

#114 Add Sharding Support
  dis_snek/client.py
  dis_snek/gateway.py
  dis_snek/state.py
Labels: enhancement, breaking

#122 Github Repo Changes
  CONTRIBUTING.md
  README.md
Labels: documentation
