Repository NAFTeam/NAFF, pull requests merged in 2022-07, with the labels that each got.

#542 feat: channel.Set perms
  naff/models/discord/channel.py
Labels: New Feature::Library

#545 feat: Prevent processors from modifying payloads
  naff/api/gateway/gateway.py
Labels: Bug::Library, Improvement

#546 feat: Add support for app_permissions field for interactions
  naff/models/naff/context.py
Labels: New Feature::Discord

#538 feat: Support multiple clients in the same process
  callback.py
  naff/client/client.py
  naff/models/naff/command.py
  naff/models/naff/extension.py
  naff/models/naff/listener.py
  naff/models/naff/prefixed_commands.py
Labels: Improvement, New Feature::Library

#550 Fix: endpoint/resource ratelimit distinction and handling
  naff/api/http/http_client.py
Labels: New Feature::Discord

#551 fix: channel edit error when ratelimited
  naff/models/discord/channel.py
Labels: Bug::Library

#547 feat: simple logging
  naff/client/client.py
Labels: New Feature::Library

#552 feat: Add gui_position to channel objects
  naff/client/smart_cache.py
  naff/models/discord/channel.py
  naff/models/discord/guild.py
Labels: Improvement, New Feature::Library

#539 feat: Add auto-shard support
  docs/src/API Reference/AutoShardClient.md
  docs/src/Guides/80 Sharding.md
  naff/api/events/internal.py
  naff/api/gateway/gateway.py
  naff/api/gateway/state.py
  naff/api/http/http_client.py
  naff/client/__init__.py
  naff/client/auto_shard_client.py
  naff/client/client.py
  naff/client/const.py
  naff/models/discord/guild.py
  naff/models/naff/active_voice_state.py
Labels: New Feature::Library

#548 Feat: Logging alternative to #547
  docs/src/Guides/90 Example.md
  naff/api/events/processors/_template.py
  naff/api/events/processors/auto_mod.py
  naff/api/events/processors/channel_events.py
  naff/api/events/processors/guild_events.py
  naff/api/events/processors/member_events.py
  naff/api/events/processors/message_events.py
  naff/api/events/processors/reaction_events.py
  naff/api/events/processors/role_events.py
  naff/api/events/processors/stage_events.py
  naff/api/events/processors/thread_events.py
  naff/api/events/processors/user_events.py
  naff/api/events/processors/voice_events.py
  naff/api/gateway/gateway.py
  naff/api/gateway/state.py
  naff/api/gateway/websocket.py
  naff/api/http/http_client.py
  naff/api/voice/player.py
  naff/api/voice/voice_gateway.py
  naff/client/auto_shard_client.py
  naff/client/client.py
  naff/client/const.py
  naff/client/mixins/serialization.py
  naff/client/smart_cache.py
  naff/client/utils/attr_utils.py
  naff/client/utils/input_utils.py
  naff/ext/debug_extension/__init__.py
  naff/ext/prefixed_help.py
  naff/models/discord/auto_mod.py
  naff/models/discord/channel.py
  naff/models/discord/enums.py
  naff/models/discord/guild.py
  naff/models/discord/user.py
  naff/models/naff/active_voice_state.py
  naff/models/naff/application_commands.py
  naff/models/naff/command.py
  naff/models/naff/context.py
  naff/models/naff/extension.py
  naff/models/naff/tasks/task.py
Labels: New Feature::Library

#553 NAFF 1.5.0
  .github/workflows/pytest-pr.yml
  .github/workflows/pytest-push.yml
  docs/src/API Reference/AutoShardClient.md
  docs/src/Guides/80 Sharding.md
  docs/src/Guides/90 Example.md
  naff/api/events/discord.py
  naff/api/events/internal.py
  naff/api/events/processors/__init__.py
  naff/api/events/processors/_template.py
  naff/api/events/processors/auto_mod.py
  naff/api/events/processors/channel_events.py
  naff/api/events/processors/guild_events.py
  naff/api/events/processors/member_events.py
  naff/api/events/processors/message_events.py
  naff/api/events/processors/reaction_events.py
  naff/api/events/processors/role_events.py
  naff/api/events/processors/stage_events.py
  naff/api/events/processors/thread_events.py
  naff/api/events/processors/user_events.py
  naff/api/events/processors/voice_events.py
  naff/api/gateway/gateway.py
  naff/api/gateway/state.py
  naff/api/gateway/websocket.py
  naff/api/http/http_client.py
  naff/api/http/http_requests/guild.py
  naff/api/voice/player.py
  naff/api/voice/voice_gateway.py
  naff/client/__init__.py
  naff/client/auto_shard_client.py
  naff/client/client.py
  naff/client/const.py
  naff/client/mixins/serialization.py
  naff/client/smart_cache.py
  naff/client/utils/attr_utils.py
  naff/client/utils/input_utils.py
  naff/ext/debug_extension/__init__.py
  naff/ext/prefixed_help.py
  naff/models/discord/__init__.py
  naff/models/discord/auto_mod.py
  naff/models/discord/channel.py
  naff/models/discord/enums.py
  naff/models/discord/guild.py
  naff/models/discord/user.py
  naff/models/discord/user.pyi
  naff/models/naff/__init__.py
  naff/models/naff/active_voice_state.py
  naff/models/naff/application_commands.py
  naff/models/naff/callback.py
  naff/models/naff/command.py
  naff/models/naff/context.py
  naff/models/naff/extension.py
  naff/models/naff/listener.py
  naff/models/naff/prefixed_commands.py
  naff/models/naff/tasks/task.py
  pyproject.toml
  setup.py
  tests/test_protocols.py
Labels: Improvement

#559 fix: check min/max value in sync comparison
  naff/models/naff/application_commands.py
Labels: Bug::Library

#560 1.6.0
  .pre-commit-config.yaml
  docs/src/Guides/03 Creating Commands.md
  naff/models/discord/user.py
  naff/models/naff/annotations/slash.py
  naff/models/naff/application_commands.py
  naff/models/naff/prefixed_commands.py
  pyproject.toml
Labels: Bug::Library, New Feature::Library

#561 feat: add .reaction and .reaction_count to MessageReaction events
  naff/api/events/discord.py
  naff/api/events/processors/reaction_events.py
Labels: Improvement, New Feature::Library

#562 fix: guilds get 5 free stickers
  naff/client/const.py
Labels: New Feature::Discord

#571 fix: channel_mention regex no longer assumes max length
  naff/models/discord/message.py
Labels: Bug::Library

#572 1.7.0
  naff/__init__.py
  naff/api/events/discord.py
  naff/api/events/processors/reaction_events.py
  naff/client/const.py
  naff/models/discord/message.py
  naff/models/discord/reaction.py
  naff/models/naff/application_commands.py
  pyproject.toml
  setup.py
  tests/test_bot.py
Labels: Bug::Library, Improvement, New Feature::Discord, New Feature::Library, ci::Fix

#574 fix: proeperly remove alias for prefixed cmd's remove_command
  naff/models/naff/prefixed_commands.py
Labels: Bug::Library

#575 refactor: improve adding prefixed commands
  naff/client/client.py
  naff/models/naff/prefixed_commands.py
Labels: Improvement

#573 feat: Convert `client.on_error` into a proper event
  naff/api/events/internal.py
  naff/client/auto_shard_client.py
  naff/client/client.py
Labels: Improvement, New Feature::Library

#570 feat: Allow audio pre-buffering
  naff/api/voice/audio.py
  naff/api/voice/player.py
Labels: New Feature::Library

#567 Tests
  naff/models/discord/emoji.py
  naff/models/naff/cooldowns.py
  tests/consts.py
  tests/test_audio.mp3
  tests/test_bot.py
  tests/test_cooldowns.py
  tests/test_emoji.py
  tests/utils.py
Labels: Bug::Library, Help wanted, ci::Addition, ci::Fix
