Repository NAFTeam/NAFF, pull requests merged in 2022-08, with the labels that each got.

#588 feat: add client.owner_ids
  naff/client/client.py
  naff/models/naff/checks.py
Labels: New Feature::Library

#590 feat: update user.pyi
  naff/models/discord/user.pyi
Labels: Improvement

#596 fix: Channel pain points
  naff/models/discord/channel.py
Labels: Bug::Library, Improvement

#594 feat: support new ws resume url
  naff/api/gateway/gateway.py
  naff/api/gateway/websocket.py
Labels: Improvement, New Feature::Discord

#598 feat: add support for getting a threads message
  naff/models/discord/channel.py
  naff/models/discord/message.py
Labels: New Feature::Library

#595 fix: unset ready on reconnect
  naff/api/gateway/gateway.py
  naff/api/gateway/state.py
  naff/api/gateway/websocket.py
  naff/client/client.py
Labels: Bug::Library

#609 fix: make fields for automod action optional
  naff/models/discord/auto_mod.py
Labels: Bug::Library

#610 feat: Allow tasks to redefine their triggers by returning a trigger
  naff/models/naff/tasks/task.py
Labels: Improvement, New Feature::Library

#608 fix: Ensure sets can be serialized
  naff/api/http/http_client.py
  naff/api/http/http_requests/guild.py
  naff/client/utils/serializer.py
  naff/models/discord/role.py
Labels: Improvement

#585 feat: add hybrid commands
  docs/src/API Reference/models/Naff/hybrid_commands.md
  docs/src/API Reference/models/Naff/index.md
  docs/src/Guides/03 Creating Commands.md
  naff/client/client.py
  naff/models/naff/__init__.py
  naff/models/naff/context.py
  naff/models/naff/extension.py
  naff/models/naff/hybrid_commands.py
  naff/models/naff/prefixed_commands.py
  tests/test_protocols.py
Labels: New Feature::Library, Requires Review

#611 feat: add listener shortcut to event objects
  naff/api/events/internal.py
Labels: New Feature::Library

#601 feat: implement REST chunking
  naff/api/events/processors/guild_events.py
  naff/client/client.py
  naff/models/discord/guild.py
Labels: Improvement, New Feature::Library

#612 fix: pass error in extension_error handler
  naff/models/naff/command.py
Labels: Bug::Library

#602 feat: Sentry Integration
  docs/src/Guides/24 Error Tracking.md
  naff/ext/sentry.py
  setup.py
Labels: New Feature::Library

#614 fix: Fix localisation syncing
  naff/api/http/http_requests/interactions.py
  naff/models/naff/application_commands.py
  naff/models/naff/localisation.py
Labels: Bug::Library, Bug::Discord
