Repository NAFTeam/NAFF, pull requests merged in 2022-03, with the labels that each got.

#339 feat: Add `create_news_channel` method.
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/guild.py
Labels: Improvement

#338 feat: Properly process permission overwrites on channel create
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/guild.py
Labels: Improvement

#353 fix: Indentation for `add_permission` method
  dis_snek/models/discord/channel.py
Labels: Bug

#355 fix: Fix some bad Type Annotations
  dis_snek/models/discord/channel.py
  dis_snek/models/snek/application_commands.py
  dis_snek/models/snek/command.py
  dis_snek/models/snek/listener.py
Labels: Bug

#347 fix: Allow standalone instances to use `guild.fetch_channel`
  dis_snek/api/gateway/state.py
  dis_snek/client/client.py
  dis_snek/models/discord/guild.py
Labels: Improvement

#349 chore: Bump deps
  pyproject.toml
Labels: Improvement

#350 fix: Remove `to_dict` calls in `list_converter`
  dis_snek/client/utils/converters.py
Labels: Bug

#351 feat: Filter away `MISSING` for all params
  dis_snek/api/http/http_client.py
  dis_snek/api/http/http_requests/reactions.py
Labels: Improvement

#354 fix: Make channel creation actually add to cache
  dis_snek/api/events/processors/channel_events.py
Labels: Bug

#356 feat💥: add bot argument to generate_prefixes
  dis_snek/client/client.py
Labels: Improvement

#352 refactor: Use attrs modern api
  dis_snek/api/events/discord.py
  dis_snek/api/events/internal.py
  dis_snek/api/gateway/state.py
  dis_snek/client/mixins/serialization.py
  dis_snek/client/smart_cache.py
  dis_snek/client/utils/attr_utils.py
  dis_snek/client/utils/attr_utils.pyi
  dis_snek/client/utils/cache.py
  dis_snek/ext/paginators.py
  dis_snek/models/discord/activity.py
  dis_snek/models/discord/application.py
  dis_snek/models/discord/asset.py
  dis_snek/models/discord/base.py
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/color.py
  dis_snek/models/discord/components.py
  dis_snek/models/discord/embed.py
  dis_snek/models/discord/emoji.py
  dis_snek/models/discord/file.py
  dis_snek/models/discord/guild.py
  dis_snek/models/discord/message.py
  dis_snek/models/discord/modal.py
  dis_snek/models/discord/reaction.py
  dis_snek/models/discord/role.py
  dis_snek/models/discord/scheduled_event.py
  dis_snek/models/discord/snowflake.py
  dis_snek/models/discord/stage_instance.py
  dis_snek/models/discord/sticker.py
  dis_snek/models/discord/team.py
  dis_snek/models/discord/thread.py
  dis_snek/models/discord/user.py
  dis_snek/models/discord/webhooks.py
  dis_snek/models/snek/application_commands.py
  dis_snek/models/snek/auto_defer.py
  dis_snek/models/snek/command.py
  dis_snek/models/snek/context.py
Labels: Improvement

#357 fix: Update `create_guild_from_guild_template` icon type hinting
  dis_snek/client/client.py
Labels: Bug

#364 fix: Modify the correct member's nickname
  dis_snek/models/discord/user.py
Labels: Bug

#359 Improvements to create guild from template
  dis_snek/client/client.py
Labels: Improvement

#361 refactor: Use `from_list` wherever applicable
  dis_snek/api/events/processors/user_events.py
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/embed.py
  dis_snek/models/discord/guild.py
  dis_snek/models/discord/team.py
  dis_snek/models/discord/thread.py
Labels: Improvement

#358 feat: Cleanup http methods
  dis_snek/api/http/http_requests/bot.py
  dis_snek/api/http/http_requests/channels.py
  dis_snek/api/http/http_requests/emojis.py
  dis_snek/api/http/http_requests/guild.py
  dis_snek/api/http/http_requests/interactions.py
  dis_snek/api/http/http_requests/members.py
  dis_snek/api/http/http_requests/messages.py
  dis_snek/api/http/http_requests/reactions.py
  dis_snek/api/http/http_requests/scheduled_events.py
  dis_snek/api/http/http_requests/stickers.py
  dis_snek/api/http/http_requests/threads.py
  dis_snek/api/http/http_requests/users.py
  dis_snek/api/http/http_requests/webhooks.py
  dis_snek/models/discord/guild.py
Labels: Improvement

#366 feat: Add activity related object classes
  dis_snek/models/discord/activity.py
  dis_snek/models/discord/enums.py
  dis_snek/models/discord/timestamp.py
Labels: Improvement

#365 feat💥: remove request_fallback args from cache
  dis_snek/api/events/processors/channel_events.py
  dis_snek/api/events/processors/guild_events.py
  dis_snek/api/events/processors/member_events.py
  dis_snek/api/events/processors/message_events.py
  dis_snek/api/events/processors/role_events.py
  dis_snek/api/events/processors/user_events.py
  dis_snek/client/smart_cache.py
Labels: Improvement

#346 fix/feat: ability to use asyncio.run with Snake.start and Snake.start_gateway
  dis_snek/api/gateway/gateway.py
  dis_snek/api/http/http_client.py
  dis_snek/client/client.py
  dis_snek/ext/debug_scale/__init__.py
  dis_snek/ext/paginators.py
  dis_snek/models/snek/tasks/task.py
  dis_snek/models/snek/wait.py
Labels: Improvement

#363 feat: Add `@Snake.listen` alias
  dis_snek/client/client.py
Labels: Improvement

#371 fix: Missing message flag
  dis_snek/models/discord/enums.py
Labels: Improvement

#374 refactor: remove pointless regex from get_first_word
  dis_snek/client/utils/input_utils.py
Labels: Improvement

#368 feat: Everything thread related
  dis_snek/client/smart_cache.py
  dis_snek/models/discord/channel.py
Labels: Improvement

#372 fix: Capture as many channel mentions as possible
  dis_snek/models/discord/message.py
Labels: Bug

#360 feat: Add support for Annotated[]
  dis_snek/models/snek/application_commands.py
  dis_snek/models/snek/command.py
Labels: Improvement

#380 fix: adjust `define` typehinting
  dis_snek/client/utils/attr_utils.pyi
Labels: Bug

#379 fix: Create entire new channel object if the channel type changes
  dis_snek/client/smart_cache.py
  dis_snek/models/discord/channel.py
Labels: Bug

#376 docs: Added `typing.BinaryIO` to possible parameters for `guild.create_custom_emoji`
  dis_snek/models/discord/guild.py
Labels: Improvement, On-Hold

#382 fix: Message processing if not fully data is given
  dis_snek/models/discord/message.py
Labels: Bug

#394 fix: Add __all__ to all remaining files, and add a linter to prevent …
  .pre-commit-config.yaml
  dis_snek/api/events/discord.py
  dis_snek/api/events/internal.py
  dis_snek/api/http/http_requests/__init__.py
  dis_snek/api/http/http_requests/bot.py
  dis_snek/api/http/http_requests/channels.py
  dis_snek/api/http/http_requests/emojis.py
  dis_snek/api/http/http_requests/guild.py
  dis_snek/api/http/http_requests/interactions.py
  dis_snek/api/http/http_requests/members.py
  dis_snek/api/http/http_requests/messages.py
  dis_snek/api/http/http_requests/reactions.py
  dis_snek/api/http/http_requests/scheduled_events.py
  dis_snek/api/http/http_requests/stickers.py
  dis_snek/api/http/http_requests/threads.py
  dis_snek/api/http/http_requests/users.py
  dis_snek/api/http/http_requests/webhooks.py
  dis_snek/client/smart_cache.py
  dis_snek/models/discord/modal.py
  dis_snek/models/snek/annotations/argument.py
  dis_snek/models/snek/annotations/slash.py
  tests/consts.py
  tests/test_cache.py
Labels: Bug, Improvement

#387 fix: Various issues with `add_permission` method (see desc.)
  dis_snek/models/discord/channel.py
Labels: Bug

#399 chore(README): Another way to explore examples
  README.md
Labels: Documentation

#385 feat: use overloads to better type get_context
  dis_snek/client/client.py
Labels: Improvement

#386 feat: Add handy methods to PermissionOverwrite
  dis_snek/models/discord/channel.py
Labels: Improvement

#401 feat(Snake): Allow `True` to be passed as `auto_defer`
  dis_snek/client/client.py
Labels: Improvement

#395 fix💥: Various issues with channel inheritance
  dis_snek/models/discord/channel.py
Labels: Bug

#384 refactor💥: Simplify thread create into one method
  dis_snek/api/http/http_requests/threads.py
  dis_snek/models/discord/channel.py
Labels: Improvement

#405 feat: Add specific thread create methods
  dis_snek/models/discord/channel.py
Labels: Improvement

#406 feat: Implement missing events
  dis_snek/api/events/discord.py
  dis_snek/api/events/processors/guild_events.py
  dis_snek/api/events/processors/message_events.py
Labels: Improvement

#400 feat: Allow cleaner syntax for slash command groups/subcommands creation
  dis_snek/client/client.py
  dis_snek/models/snek/application_commands.py
Labels: Missing Feature, Improvement

#416 docs: A handful more annotations
  .pre-commit-config.yaml
  dis_snek/api/gateway/gateway.py
  dis_snek/client/client.py
  dis_snek/client/smart_cache.py
  dis_snek/ext/debug_scale/__init__.py
  dis_snek/ext/debug_scale/debug_application_cmd.py
  dis_snek/models/snek/listener.py
Labels: Improvement

#370 Voice Support
  .github/workflows/pytest.yml
  .readthedocs.yaml
  MANIFEST.in
  dis_snek/api/events/processors/voice_events.py
  dis_snek/api/gateway/gateway.py
  dis_snek/api/gateway/state.py
  dis_snek/api/gateway/websocket.py
  dis_snek/api/voice/__init__.py
  dis_snek/api/voice/audio.py
  dis_snek/api/voice/encryption.py
  dis_snek/api/voice/opus.py
  dis_snek/api/voice/player.py
  dis_snek/api/voice/voice_gateway.py
  dis_snek/bin/opus-x64.dll
  dis_snek/bin/opus-x86.dll
  dis_snek/client/client.py
  dis_snek/client/errors.py
  dis_snek/client/smart_cache.py
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/guild.py
  dis_snek/models/discord/user.py
  dis_snek/models/discord/voice_state.py
  dis_snek/models/snek/__init__.py
  dis_snek/models/snek/active_voice_state.py
  dis_snek/models/snek/context.py
  docs/requirements.txt
  docs/src/API Reference/API_Communication/voice/audio.md
  docs/src/API Reference/API_Communication/voice/player.md
  docs/src/API Reference/API_Communication/voice/voice_gateway.md
  docs/src/API Reference/models/Snek/active_voice_state.md
  docs/src/API Reference/models/Snek/index.md
  docs/src/Guides/22 Voice.md
  pyproject.toml
  setup.py
Labels: New Feature
