Repository NAFTeam/NAFF, pull requests merged in 2022-01, with the labels that each got.

#139 fix: rewrite Role.guild as property; fixes broken Role.members
  dis_snek/models/discord_objects/role.py
Labels: bug

#202 fix: Missing properties in `GuildChannel.clone`
  dis_snek/models/discord/channel.py
Labels: Missing Feature

#201 refactor!: ChannelUpdate now has before and after args just like all other events
  dis_snek/api/events/discord.py
  dis_snek/api/events/processors/channel_events.py
Labels: Missing Feature

#212 fix: Adjust standart emoji string
  dis_snek/models/discord/emoji.py
Labels: Bug

#213 Add conventional commits to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Documentation

#216 fix: Subcommand improvements
  dis_snek/models/snek/application_commands.py
Labels: Bug, Improvement

#217 HTTP Request Improvements
  dis_snek/api/http/http_client.py
  dis_snek/api/http/route.py
  dis_snek/models/discord/message.py
Labels: Improvement

#218 fix: Improve guild prune (see desc.)
  dis_snek/api/http/http_requests/guild.py
  dis_snek/models/discord/guild.py
Labels: Bug

#228 fix: Keep local member model in sync when we add or remove roles
  dis_snek/models/discord/user.py
Labels: Bug

#231 fix: If a message is from a DM, don't try setting its guild_id
  dis_snek/client/smart_cache.py
Labels: Bug

#221 feat: Respect http buckets in http client for rate limiting
  dis_snek/api/http/http_client.py
  dis_snek/api/http/route.py
  dis_snek/ext/debug_scale/utils.py
Labels: Improvement

#227 fix💥: Broken guild get/fetch thread
  dis_snek/models/discord/guild.py
Labels: Bug
