Repository NAFTeam/NAFF, pull requests merged in 2022-09, with the labels that each got.

#618 feat: implement dunder str in httpexception
  naff/client/errors.py
Labels: Improvement, New Feature::Library

#616 fix: dont rechunk guilds on reconnect
  naff/api/events/processors/guild_events.py
Labels: Bug::Library

#615 fix: handle guild not existing in the cache
  naff/client/smart_cache.py
Labels: Bug::Library

#619 fix: restore ability to resume ++
  naff/api/gateway/gateway.py
  naff/api/gateway/websocket.py
Labels: Bug::Library

#623 feat: Support mention spam mod
  naff/models/discord/auto_mod.py
  naff/models/discord/enums.py
Labels: New Feature::Discord

#622 fix: dont use resume_url on invalid session
  naff/api/gateway/gateway.py
Labels: Bug::Library

#620 feat: use async iterator to speedup http chunking
  naff/models/discord/guild.py
  naff/models/misc/iterator.py
Labels: Improvement, New Feature::Library

#624 NAFF 1.10.0
  naff/api/events/processors/guild_events.py
  naff/api/gateway/gateway.py
  naff/api/gateway/websocket.py
  naff/client/errors.py
  naff/client/smart_cache.py
  naff/models/discord/auto_mod.py
  naff/models/discord/enums.py
  naff/models/discord/guild.py
  naff/models/misc/iterator.py
  pyproject.toml
Labels: Improvement

#626 fix: Typing of some create_guild parameters
  naff/api/http/http_requests/guild.py
  naff/models/discord/guild.py
Labels: Documentation, Improvement

#627 fix: positional argument error in fetch messages
  naff/models/discord/channel.py
Labels: Bug::Library

#634 fix: Requests Mixins aren't ABCs
  naff/api/http/http_requests/channels.py
  naff/api/http/http_requests/emojis.py
  naff/api/http/http_requests/interactions.py
  naff/api/http/http_requests/members.py
  naff/api/http/http_requests/messages.py
Labels: ci::Fix

#635 feat 💥: delay non-raw listeners until client ready
  naff/client/client.py
  naff/models/naff/listener.py
Labels: New Feature::Library

#636 refactor 💥: Update and organise event bases
  naff/api/events/__init__.py
  naff/api/events/base.py
  naff/api/events/discord.py
  naff/api/events/internal.py
Labels: Bug::Library

#630 feat: support component only messages
  naff/client/mixins/send.py
Labels: New Feature::Discord

#631 feat 💥: fire async start methods as soon as possible
  naff/client/client.py
Labels: Improvement

#633 fix: handle discord not sending an error attrib in exceptions
  naff/client/errors.py
Labels: Bug::Discord

#632 feat: restore asyncio debug in debug ext
  naff/ext/debug_extension/__init__.py
Labels: New Feature::Library

#651 docs: remove redundant todos
  naff/api/gateway/gateway.py
  naff/api/http/http_requests/guild.py
  naff/api/voice/encryption.py
  naff/api/voice/opus.py
  naff/client/mixins/serialization.py
  naff/models/discord/base.py
  naff/models/discord/color.py
  naff/models/discord/guild.py
  tests/test_bot.py
Labels: Documentation

#649 feat: serialise any naff-objects passed in request payloads
  naff/api/http/http_client.py
Labels: Improvement, New Feature::Library

#628 feat: cache app cmd perm updates
  naff/api/events/discord.py
  naff/api/events/processors/__init__.py
  naff/api/events/processors/integrations.py
  naff/client/client.py
  naff/models/discord/__init__.py
  naff/models/discord/app_perms.py
  naff/models/discord/enums.py
  naff/models/discord/guild.py
  naff/models/naff/application_commands.py
Labels: New Feature::Library

#646 feat 💥: Forums rewrite
  naff/api/events/discord.py
  naff/api/events/processors/thread_events.py
  naff/api/http/http_requests/channels.py
  naff/api/http/http_requests/threads.py
  naff/models/discord/channel.py
Labels: New Feature::Discord, New Feature::Library

#650 fix💥: handle errors when parsing http exceptions
  naff/client/client.py
  naff/client/errors.py
Labels: Bug::Library

#656 NAFF 1.11.1
  naff/client/errors.py
  naff/models/naff/application_commands.py
  pyproject.toml
Labels: Bug::Library

#647 fix💥: Make naff always use the correct logger (v2)
  naff/api/events/processors/message_events.py
  naff/api/gateway/gateway.py
  naff/api/gateway/state.py
  naff/api/gateway/websocket.py
  naff/api/http/http_client.py
  naff/api/voice/player.py
  naff/api/voice/voice_gateway.py
  naff/client/auto_shard_client.py
  naff/client/client.py
  naff/client/const.py
  naff/client/mixins/serialization.py
  naff/client/smart_cache.py
  naff/client/utils/attr_utils.py
  naff/client/utils/input_utils.py
  naff/ext/debug_extension/__init__.py
  naff/ext/debug_extension/debug_application_cmd.py
  naff/ext/prefixed_help.py
  naff/ext/sentry.py
  naff/models/discord/auto_mod.py
  naff/models/discord/channel.py
  naff/models/discord/enums.py
  naff/models/discord/guild.py
  naff/models/discord/user.py
  naff/models/naff/active_voice_state.py
  naff/models/naff/application_commands.py
  naff/models/naff/context.py
  naff/models/naff/extension.py
  naff/models/naff/tasks/task.py
Labels: On-Hold
