Repository NAFTeam/NAFF, pull requests merged in 2022-05, with the labels that each got.

#464 feat: Add support for application cmds attrib of audit log
  dis_snek/client/utils/deserialise_app_cmds.py
  dis_snek/models/discord/guild.py
  dis_snek/models/snek/application_commands.py
Labels: New Feature

#468 Tests bot
  .github/workflows/pytest.yml
  pyproject.toml
  pytest.ini
  tests/LordOfPolls.png
  tests/test_bot.py
  tests/tests_test_audio.mp3
Labels: Improvement

#477 feat: Support auto-mod
  naff/models/discord/enums.py
Labels: Missing Feature

#481 docs: correct grammar in `ThreadableMixin`.
  naff/models/discord/channel.py
Labels: Documentation

#472 feat: embed types
  naff/models/discord/embed.py
  naff/models/discord/enums.py
Labels: Improvement, On-Hold

#480 feat: move formdata processing to http_client.request
  naff/api/http/http_client.py
  naff/api/http/http_requests/channels.py
  naff/api/http/http_requests/emojis.py
  naff/api/http/http_requests/guild.py
  naff/api/http/http_requests/interactions.py
  naff/api/http/http_requests/members.py
  naff/api/http/http_requests/messages.py
  naff/api/http/http_requests/scheduled_events.py
  naff/api/http/http_requests/stickers.py
  naff/api/http/http_requests/threads.py
  naff/api/http/http_requests/users.py
  naff/api/http/http_requests/webhooks.py
  naff/client/mixins/send.py
  naff/models/discord/channel.py
  naff/models/discord/guild.py
  naff/models/discord/message.py
  naff/models/discord/thread.py
  naff/models/discord/user.py
  naff/models/discord/webhooks.py
  naff/models/naff/context.py
Labels: Improvement

#486 fix: Allow dispatch in a channel the bot has no data on channel
  naff/client/client.py
Labels: Bug

#493 feat: add Typing context manager
  naff/models/discord/channel.py
  naff/models/misc/__init__.py
  naff/models/misc/context_manager.py
Labels: New Feature

#494 feat: Make `Extension.name` public
  naff/models/naff/extension.py
Labels: New Feature

#495 feat: Add member.edit
  naff/models/discord/user.py
Labels: Missing Feature

#496 feat: add asset.as_url
  naff/models/discord/asset.py
Labels: New Feature

#492 feat: Add disconnect alias to VoiceChannel
  naff/client/errors.py
  naff/models/discord/channel.py
Labels: New Feature

#499 Private channel fix
  naff/client/smart_cache.py
  naff/models/discord/channel.py
  naff/models/discord/message.py
Labels: Bug

#500 fix: Ensure subprocess is killed on linux
  naff/api/voice/audio.py
Labels: Bug

#501 fix: Allow audio/args with spaces in them
  naff/api/voice/audio.py
Labels: Missing Feature

#503 fix: Kill subprocess instead of terminate
  naff/api/voice/audio.py
Labels: Bug

#502 feat: support nsfw field in app cmds
  naff/models/naff/application_commands.py
Labels: New Feature
