Repository NAFTeam/NAFF, pull requests merged in 2022-04, with the labels that each got.

#423 feat: Allow passing keyword arguments into extension methods
  dis_snek/client/client.py
Labels: New Feature

#424 docs: Add guides example about #423
  docs/src/Guides/20 Scales.md
Labels: Documentation

#432 feat: add Modal callbacks
  dis_snek/client/client.py
  dis_snek/models/snek/application_commands.py
  dis_snek/models/snek/scale.py
Labels: New Feature

#430 Switch to api V10
  dis_snek/api/http/http_client.py
  dis_snek/api/http/route.py
  dis_snek/client/const.py
Labels: Improvement

#427 feat: Send error to channel with default error handlers
  dis_snek/client/client.py
Labels: New Feature, Improvement

#440 fix: Add missing intents for v10
  dis_snek/models/discord/enums.py
Labels: Missing Feature

#441 feat: support multi-scale unloading
  dis_snek/client/client.py
Labels: Improvement

#438 feat: Add mypy plugin. This adds support for our custom attrs wrapper.
  dis_snek/ext/mypy/__init__.py
  pyproject.toml
Labels: New Feature

#443 build: Add speed up install extra deps
  .github/workflows/pytest.yml
  setup.py
Labels: Improvement

#442 refactor💥: Re-order client args, and enforce kw_only
  dis_snek/client/client.py
Labels: Improvement

#439 feat: sync app-cmds on scale (un)loading
  dis_snek/client/client.py
Labels: Missing Feature

#445 feat💥: Localisation support
  dis_snek/client/client.py
  dis_snek/client/const.py
  dis_snek/client/utils/attr_utils.py
  dis_snek/client/utils/attr_utils.pyi
  dis_snek/models/snek/application_commands.py
  dis_snek/models/snek/command.py
  dis_snek/models/snek/context.py
  dis_snek/models/snek/localisation.py
  docs/src/API Reference/models/Snek/index.md
  docs/src/API Reference/models/Snek/localisation.md
  docs/src/Guides/23 Localisation.md
Labels: Missing Feature

#451 feat: Support async entrypoint for scales
  dis_snek/client/client.py
  dis_snek/models/snek/application_commands.py
  dis_snek/models/snek/scale.py
Labels: New Feature

#457 feat 🔥: Handle unknown channel types without data-loss
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/enums.py
Labels: Bug, Improvement

#460 fix: various slash command fixes
  dis_snek/models/snek/annotations/slash.py
  dis_snek/models/snek/application_commands.py
Labels: Bug

#461 fix💥: GuildStageVoice no longer inherits from GuildVoice
  dis_snek/models/discord/channel.py
Labels: Bug
