Repository NAFTeam/NAFF, pull requests merged in 2022-02, with the labels that each got.

#235 Add target property to interaction context
  dis_snek/models/snek/context.py
Labels: Missing Feature

#251 feat: added GuildEvent.guild property
  dis_snek/api/events/internal.py
Labels: Missing Feature

#252 refactor: Member.has_role
  dis_snek/models/discord/user.py
Labels: Improvement

#254 FIX: KeyError in `place_member_data()`
  dis_snek/client/smart_cache.py
Labels: Bug

#250 fix: behaviour of role add and delete events
  dis_snek/api/events/discord.py
  dis_snek/api/events/processors/role_events.py
Labels: Bug, Improvement

#257 feat: Update smart_cache
  dis_snek/api/events/processors/channel_events.py
  dis_snek/api/events/processors/guild_events.py
  dis_snek/api/events/processors/member_events.py
  dis_snek/api/events/processors/message_events.py
  dis_snek/api/events/processors/reaction_events.py
  dis_snek/api/events/processors/role_events.py
  dis_snek/api/events/processors/thread_events.py
  dis_snek/api/events/processors/user_events.py
  dis_snek/client/client.py
  dis_snek/client/smart_cache.py
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/guild.py
  dis_snek/models/discord/message.py
  dis_snek/models/discord/role.py
  dis_snek/models/discord/scheduled_event.py
  dis_snek/models/discord/sticker.py
  dis_snek/models/discord/thread.py
  dis_snek/models/discord/user.py
  docs/src/Guides/4 Context Menus.md
Labels: Improvement

#265 feat: Add Attachment Option to Application Command
  dis_snek/models/discord/message.py
  dis_snek/models/snek/annotations/slash.py
  dis_snek/models/snek/application_commands.py
  dis_snek/models/snek/context.py
Labels: New Feature

#186 feat: basic modal support
  dis_snek/api/events/discord.py
  dis_snek/client/client.py
  dis_snek/models/discord/__init__.py
  dis_snek/models/discord/enums.py
  dis_snek/models/discord/modal.py
  dis_snek/models/snek/application_commands.py
  dis_snek/models/snek/context.py
Labels: New Feature

#267 DOCS: add modal and attachment option docs, and refactor some docs
  docs/src/Guides/01 Getting Started.md
  docs/src/Guides/02 Creating Your Bot.md
  docs/src/Guides/03 Creating Commands.md
  docs/src/Guides/04 Context Menus.md
  docs/src/Guides/05 Components.md
  docs/src/Guides/06 Modals.md
  docs/src/Guides/10 Events.md
  docs/src/Guides/20 Scales.md
  docs/src/Guides/21 Advanced Scale Usage.md
  docs/src/Guides/30 Pagination.md
  docs/src/Guides/90 Example.md
  docs/src/Guides/99 Migration From D.py.md
  docs/src/images/Modals/modal_example.png
  docs/src/images/Modals/modal_example_customisiblity.png
Labels: Documentation

#266 feat: Allow using event typehint to define listener
  dis_snek/models/snek/listener.py
Labels: New Feature

#270 feat: audit log support
  dis_snek/api/http/http_requests/guild.py
  dis_snek/models/discord/enums.py
  dis_snek/models/discord/guild.py
Labels: New Feature

#278 feat: Allow import all triggers from `ext.tasks`
  dis_snek/ext/tasks/__init__.py
Labels: Improvement

#277 FIX: VoiceStateUpdate was not updating the cached channel obj after a member left
  dis_snek/client/smart_cache.py
Labels: Bug

#272 FEAT: add ability to get mutual guilds / member instances for users
  dis_snek/models/discord/user.py
Labels: Bug, Improvement

#279 perf: Remove unnecessary cache requests
  dis_snek/api/events/processors/reaction_events.py
  dis_snek/ext/debug_scale/debug_application_cmd.py
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/message.py
  dis_snek/models/snek/context.py
  dis_snek/models/snek/cooldowns.py
Labels: Improvement

#291 docs: Update readme links.
  README.md
Labels: Documentation

#292 feat: Add `ThreadChannel.archive` helper method
  dis_snek/models/discord/channel.py
Labels: New Feature

#289 refactor: Make all gets non-async, all fetches async
  dis_snek/client/client.py
  dis_snek/client/smart_cache.py
  dis_snek/models/discord/asset.py
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/guild.py
  dis_snek/models/discord/message.py
  dis_snek/models/discord/role.py
  dis_snek/models/discord/scheduled_event.py
  dis_snek/models/discord/sticker.py
  dis_snek/models/discord/thread.py
  dis_snek/models/discord/user.py
Labels: Improvement

#286 feat: Delete thread from cache in `_on_raw_thread_delete`
  dis_snek/api/events/processors/thread_events.py
  dis_snek/client/smart_cache.py
Labels: Missing Feature

#281 test: Add tests
  .flake8
  .github/pull_request_template.md
  .github/workflows/pytest.yml
  .gitignore
  .readthedocs.yaml
  dis_snek/client/smart_cache.py
  docs/requirements.txt
  pyproject.toml
  pytest.ini
  requirements.txt
  tests/__init__.py
  tests/consts.py
  tests/test_cache.py
Labels: New Feature, Improvement

#284 feat💥: Improve channel permissions (see desc.)
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/guild.py
  dis_snek/models/discord/user.py
Labels: Bug, New Feature, Documentation, Improvement

#301 fix: Various channel related type hinting.
  dis_snek/models/discord/channel.py
Labels: Bug

#299 fix: Properly handle url passed into embed image.
  dis_snek/models/discord/embed.py
Labels: Bug

#300 fix: Use correct fetch methods in `fetch_all_threads`
  dis_snek/models/discord/channel.py
Labels: Bug

#302 feat: Add getting of `GuildCategory.news_channels`.
  dis_snek/models/discord/channel.py
Labels: Improvement

#311 fix: Forgot to pass in username and avatar_url.
  dis_snek/models/discord/webhooks.py
Labels: Bug

#307 fix: Remove unnecessary returns for `remove_reaction` method.
  dis_snek/models/discord/message.py
Labels: Bug

#308 feat: add `reply` to `MessageContext`
  dis_snek/models/snek/context.py
Labels: Improvement

#315 feat: Update debug_exec.py
  dis_snek/ext/debug_scale/debug_exec.py
Labels: Improvement

#297 feat💥: Improve role icon (see desc.)
  dis_snek/models/discord/role.py
Labels: New Feature, Improvement

#304 Feat: debug scale visual improvements
  dis_snek/ext/debug_scale/__init__.py
  dis_snek/ext/debug_scale/utils.py
Labels: Improvement

#306 feat💥: allow for iterables of str for msg prefixes
  dis_snek/client/client.py
Labels: New Feature, Improvement

#309 feat: Improve todict and its usage
  dis_snek/client/utils/serializer.py
  dis_snek/models/discord/embed.py
  dis_snek/models/discord/message.py
Labels: Improvement

#312 feat: Add support for editing webhook.
  dis_snek/models/discord/webhooks.py
Labels: New Feature, Improvement

#318 fix: Mention prefix erroring out
  dis_snek/client/client.py
Labels: Bug

#303 feat💥: Improve and fix channel edit handling (see desc.)
  dis_snek/models/discord/channel.py
Labels: Improvement

#310 feat: Add support for sending multiple files.
  dis_snek/client/mixins/send.py
  dis_snek/models/discord/file.py
  dis_snek/models/discord/message.py
  dis_snek/models/discord/webhooks.py
  dis_snek/models/snek/context.py
Labels: New Feature, Improvement

#314 Feat text format
  dis_snek/client/utils/__init__.py
  dis_snek/client/utils/formatting.py
Labels: New Feature

#313 fix: Inconsistences with image data processing
  dis_snek/client/utils/input_utils.py
  dis_snek/client/utils/serializer.py
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/guild.py
  dis_snek/models/discord/user.py
  dis_snek/models/discord/webhooks.py
Labels: Bug, Improvement

#316 feat: Update debug_exec.py
  dis_snek/ext/debug_scale/debug_exec.py
Labels: Improvement

#321 feat: Add `GuildChannel.add_permission` helper method
  dis_snek/models/discord/channel.py
Labels: New Feature, Improvement

#322 refactor: Move processing of color from to_dict to a separate method.
  dis_snek/models/discord/color.py
  dis_snek/models/discord/embed.py
Labels: Improvement

#333 fix: Incorrect message fetch method used.
  dis_snek/models/discord/channel.py
Labels: Bug

#328 fix: Missing `__all__` entries in misc_utils.py
  dis_snek/client/utils/misc_utils.py
Labels: Bug

#329 feat: Webhook from_url method
  dis_snek/models/discord/webhooks.py
Labels: New Feature

#330 featfactor: client methods for command execution
  dis_snek/client/client.py
Labels: New Feature

#334 feat: Implement widget related objects and methods
  dis_snek/models/discord/guild.py
Labels: New Feature

#332 refactor: Improve method structure of reaction event.
  dis_snek/api/events/processors/reaction_events.py
Labels: Improvement

#331 feat: Add limit and after params for `fetch_reaction`
  dis_snek/models/discord/message.py
Labels: Improvement

#327 feat: Improve file open parsing
  dis_snek/models/discord/file.py
  dis_snek/models/discord/guild.py
  dis_snek/models/discord/message.py
Labels: Bug, Improvement

#326 fix💥: Inconsistent fetch_* function behaviour.
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/guild.py
  dis_snek/models/discord/scheduled_event.py
Labels: Improvement

#325 feat: Add VoiceRegion object and its relevant methods.
  dis_snek/client/client.py
  dis_snek/models/discord/channel.py
  dis_snek/models/discord/guild.py
  dis_snek/models/discord/voice_state.py
Labels: New Feature

#337 refactor: Use existing guild method in `GuildCategory.create_channel`
  dis_snek/models/discord/channel.py
Labels: Improvement

#342 fix: rename `get` to `fetch` in `Asset.save()`
  dis_snek/models/discord/asset.py
Labels: Bug

#341 fix: `get_custom_emoji` optional type hinting.
  dis_snek/models/discord/guild.py
Labels: Bug

#336 fix: Improve guild system channel flags (see desc.)
  dis_snek/models/discord/enums.py
  dis_snek/models/discord/guild.py
Labels: Documentation, Improvement

#335 docs: A half-decent list of FAQs for porting from dpy
  docs/src/Guides/99 Migration From D.py.md
Labels: Documentation
